config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :posts
  get '/posts', to: 'posts#index', as: :posts
  get '/posts/new', to: 'posts#new', as: :new_post
  get '/posts/:id', to: 'posts#show', as: :post
  post '/posts', to: 'posts#create'
  get '/posts/:id/edit', to: 'posts#edit', as: :edit_post
  patch '/posts/:id', to: 'posts#update'
  delete '/posts/:id', to: 'posts#delete'

  get '/categories/:category_id/posts', to: 'posts#index', as: :category_posts

  
  resources :uploads
  root to: 'posts#index'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :nullify
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category

  scope :ordered, -> { order(id: :desc)}
  scope :with_categories, -> {includes(:category)}
  scope :search_by_starts_with, -> (title) { where("title like ?", "#{title}%")}
  # Ex:- scope :active, -> {where(:active => true)}
end

app/models/upload.rb
class Upload < ActiveRecord::Base
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index 
      
      if params[:search].present?
        @posts = Post.search_by_starts_with(params[:search]).paginate(page: params[:page], per_page: 2)
      end

      if params[:category_id]
        @category = Category.find(params[:category_id])
        @posts = @category.posts.ordered.with_categories.paginate(page: params[:page], per_page: 2)
      end
      
      @posts ||= Post.with_categories.paginate(page: params[:page], per_page: 2)
    end

    def show 
      load_post
    end

    def new
      #load_categories
      @post = Post.new
    end
    
    def create
      @post = Post.new(post_params)
      @post.save
      redirect_to @post
    end

    def edit
      #load_categories
      load_post
    end

    def update
      load_post
      @post.update(post_params)
      redirect_to @post
    end

    def delete
      load_post
      @post.destroy
      redirect_to :posts
    end
    private

    def post_params
      params.require(:post).permit(:title, :text, :category_id)
    end

    def load_post
      @post = Post.find(params[:id])
    end

    #def load_categories
     # @categories = Category.all
    #end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
    def new
    end

    def create
      # Make an object in your bucket for your upload
      obj = S3_BUCKET.bucket(BUCKET_NAME).object(params[:file].original_filename)

      # Upload the file
      obj.put(body: params[:file].to_io)

      # Create an object for the upload
      @upload = Upload.new(
              url: obj.public_url,
          name: obj.key
          )

      # Save the upload
      if @upload.save
        redirect_to uploads_path, success: 'File successfully uploaded'
      else
        flash.now[:notice] = 'There was an error'
        render :new
      end
    end

    def index
        @uploads = Upload.all
    end
  end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>
  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.select :category_id, Category.all.map { |c| [c.name, c.id] } %>
  </div>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post "<%= @post.title %>"</h1>
<%= render partial: 'form' %>

app/views/posts/index.html.erb
<h1>
    <%= @category&.name || "ALL" %> posts
</h1>

<% if @category %>
  <%= link_to "ALL post", posts_path %>
<% end %>

<%= link_to "Create new post", new_post_path %>
<div class="posts-container">
  <% @posts.each do |post| %>  
    <div class="post">

      <%= link_to post do %>
        <h3> <%= post.title %> </h3>
      <% end %>
      <!-- <p><%= post.category.name %></p> -->
      <%= link_to post.category.name, category_posts_path(post.category)%>
      <p><%= post.created_at %></p>
      <p><%= post.text %></p>
    
    </div>
    
  <% end %>
</div>

<%= form_tag(posts_path, method: :get) do%>
  <%= text_field_tag(:search, params[:search]) %>
  <%= submit_tag("Search") %>
<% end %>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render partial: 'form' %>

app/views/posts/show.html.erb
<h1> <%= @post.title %> </h1>
<p><%= @post.category.name %></p>
<p><%= @post.created_at %></p>
<p><%= @post.text %></p>
<div class="link_container">
  <%= link_to 'Edit', edit_post_path(@post.id) %>
</div>
<div class="link_container">
  <%=
   link_to 'Delete', edit_post_path(@post.id), method: :delete,
   data: {confirm: "Are you sure?"}, remote: true 
  %>
</div>
<div class="link_container">
  <%= link_to 'Go back to posts', posts_path %>
</div>

app/views/uploads/index.html.erb
<h1>All uploads</h1>
<% @uploads.each do |upload| %>
	<div>
		<%= link_to upload.name, upload.url %>
	</div>
<% end %> 

app/views/uploads/new.html.erb
<h1>Upload a file</h1>

<%= form_tag uploads_path, enctype: 'multipart/form-data' do %>
	<%= file_field_tag :file  %>
	<%= submit_tag 'Upload file' %>
<% end %> 